# Generated by Django 2.1.9 on 2019-06-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('game_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('game_type', models.CharField(max_length=20)),
                ('json_game_state', models.TextField()),
            ],
        ),
    ]
